name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build Windows
      run: dotnet publish -r win-x64
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        path: /home/runner/work/CIManager/CIManager/CIManager/bin/Debug/net5.0/win-x64/publish/*.exe
